// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions currentPlatform() {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3lb-zJfxY42c5gR82jtLw_ky9a9nd-Gc',
    appId: '1:130652190454:web:6522064b9fbf1da4c99ed7',
    messagingSenderId: '130652190454',
    projectId: 'med-data-e1705',
    authDomain: 'med-data-e1705.firebaseapp.com',
    storageBucket: 'med-data-e1705.appspot.com',
    measurementId: 'G-YZD4SYB7EH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd6NCu_ERPux3o01dVAOJs2J4KDYRo8to',
    appId: '1:130652190454:android:e3faafed06da1dd9c99ed7',
    messagingSenderId: '130652190454',
    projectId: 'med-data-e1705',
    storageBucket: 'med-data-e1705.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnNeDqYuw1OHNq4iLpPvjnfbZkXfX19dc',
    appId: '1:130652190454:ios:31c52b88e38cfdb8c99ed7',
    messagingSenderId: '130652190454',
    projectId: 'med-data-e1705',
    storageBucket: 'med-data-e1705.appspot.com',
    iosClientId:
        '130652190454-kk2o7jjudkb07sm69eldppo3c38c7j2l.apps.googleusercontent.com',
    iosBundleId: 'com.example.getMedicineProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnNeDqYuw1OHNq4iLpPvjnfbZkXfX19dc',
    appId: '1:130652190454:ios:31c52b88e38cfdb8c99ed7',
    messagingSenderId: '130652190454',
    projectId: 'med-data-e1705',
    storageBucket: 'med-data-e1705.appspot.com',
    iosClientId:
        '130652190454-kk2o7jjudkb07sm69eldppo3c38c7j2l.apps.googleusercontent.com',
    iosBundleId: 'com.example.getMedicineProject',
  );
}
